// <auto-generated />
using System;
using DataAccessLayer.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("DataAccessLayer.Entities.Account", b =>
                {
                    b.Property<Guid?>("ClientId")
                        .HasColumnType("Guid");

                    b.Property<decimal>("CountMonetaryUnit")
                        .HasColumnType("Decimal");

                    b.Property<long>("DateOpen")
                        .HasColumnType("Int64");

                    b.Property<bool>("IsClose")
                        .HasColumnType("Boolean");

                    b.Property<bool>("IsLock")
                        .HasColumnType("Boolean");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Procent")
                        .HasColumnType("Double");

                    b.Property<int>("TypeAccount")
                        .HasColumnType("Int32");

                    b.Property<Guid>("UID")
                        .HasColumnType("Guid");

                    b.HasKey("ClientId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Customer", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Guid");

                    b.Property<string>("ChangingWorker")
                        .IsRequired()
                        .HasColumnType("Int32");

                    b.Property<long>("DateChange")
                        .HasColumnType("Int64");

                    b.Property<int>("FieldChanged")
                        .HasColumnType("Int32");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Passport")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeChanged")
                        .HasColumnType("Int32");

                    b.HasKey("UID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Account", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Customer", "Customer")
                        .WithMany("Accounts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Customer", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
